# Generated by Django 2.2.5 on 2019-11-26 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tfsapp', '0003_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Children', 'Children')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
