# Generated by Django 2.2.5 on 2019-11-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfsapp', '0008_auto_20191129_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
